# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2020-01-12 16:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Restorent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('details', models.CharField(max_length=60)),
                ('restorentImg', models.ImageField(null=True, upload_to='locations')),
                ('location', models.ForeignKey(blank=True, null='True', on_delete=django.db.models.deletion.CASCADE, to='restoapp.Location')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
